package com.bluntsoftware.ReachOut.modules.reachout.repository;

import com.bluntsoftware.ReachOut.modules.reachout.domain.Address;
import com.genx.framework.jpa.repository.GenericRepository;
import org.springframework.stereotype.Repository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.beans.factory.annotation.Qualifier;
/**
* Repository interface for table: Address.
* @author autogenerated
*/

@Repository("reachoutAddressRepository")
@Qualifier("reachout")
//@RepositoryRestResource(collectionResourceRel="reachout.Address", path="reachout/Address")
public interface AddressRepository extends GenericRepository<Address,Integer>  {

}