package com.bluntsoftware.ReachOut.modules.reachout.repository;

import com.bluntsoftware.ReachOut.modules.reachout.domain.Company;
import com.genx.framework.jpa.repository.GenericRepository;
import org.springframework.stereotype.Repository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.beans.factory.annotation.Qualifier;
/**
* Repository interface for table: Company.
* @author autogenerated
*/

@Repository("reachoutCompanyRepository")
@Qualifier("reachout")
//@RepositoryRestResource(collectionResourceRel="reachout.Company", path="reachout/Company")
public interface CompanyRepository extends GenericRepository<Company,Integer>  {

}