package com.bluntsoftware.ReachOut.modules.reachout.repository;

import com.bluntsoftware.ReachOut.modules.reachout.domain.Contactinfotag;
import com.genx.framework.jpa.repository.GenericRepository;
import org.springframework.stereotype.Repository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.beans.factory.annotation.Qualifier;
/**
* Repository interface for table: Contactinfotag.
* @author autogenerated
*/

@Repository("reachoutContactinfotagRepository")
@Qualifier("reachout")
//@RepositoryRestResource(collectionResourceRel="reachout.Contactinfotag", path="reachout/Contactinfotag")
public interface ContactinfotagRepository extends GenericRepository<Contactinfotag,Integer>  {

}