package com.bluntsoftware.ReachOut.modules.reachout.repository;

import com.bluntsoftware.ReachOut.modules.reachout.domain.Contactinfo;
import com.genx.framework.jpa.repository.GenericRepository;
import org.springframework.stereotype.Repository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.beans.factory.annotation.Qualifier;
/**
* Repository interface for table: Contactinfo.
* @author autogenerated
*/

@Repository("reachoutContactinfoRepository")
@Qualifier("reachout")
//@RepositoryRestResource(collectionResourceRel="reachout.Contactinfo", path="reachout/Contactinfo")
public interface ContactinfoRepository extends GenericRepository<Contactinfo,Integer>  {

}