package com.bluntsoftware.ReachOut.modules.reachout.repository;

import com.bluntsoftware.ReachOut.modules.reachout.domain.Contactemail;
import com.genx.framework.jpa.repository.GenericRepository;
import org.springframework.stereotype.Repository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.beans.factory.annotation.Qualifier;
/**
* Repository interface for table: Contactemail.
* @author autogenerated
*/

@Repository("reachoutContactemailRepository")
@Qualifier("reachout")
//@RepositoryRestResource(collectionResourceRel="reachout.Contactemail", path="reachout/Contactemail")
public interface ContactemailRepository extends GenericRepository<Contactemail,Integer>  {

}