package com.bluntsoftware.ReachOut.modules.reachout.repository;

import com.bluntsoftware.ReachOut.modules.reachout.domain.Contact;
import com.genx.framework.jpa.repository.GenericRepository;
import org.springframework.stereotype.Repository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.beans.factory.annotation.Qualifier;
/**
* Repository interface for table: Contact.
* @author autogenerated
*/

@Repository("reachoutContactRepository")
@Qualifier("reachout")
//@RepositoryRestResource(collectionResourceRel="reachout.Contact", path="reachout/Contact")
public interface ContactRepository extends GenericRepository<Contact,Integer>  {

}