package com.bluntsoftware.ReachOut.modules.reachout.repository;

import com.bluntsoftware.ReachOut.modules.reachout.domain.Contactinfo;
import com.bluntsoftware.ReachOut.modules.reachout.domain.Contactphone;
import com.genx.framework.jpa.repository.GenericRepository;
import org.springframework.stereotype.Repository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.beans.factory.annotation.Qualifier;
/**
* Repository interface for table: Contactphone.
* @author autogenerated
*/

@Repository("reachoutContactphoneRepository")
@Qualifier("reachout")
//@RepositoryRestResource(collectionResourceRel="reachout.Contactphone", path="reachout/Contactphone")
public interface ContactphoneRepository extends GenericRepository<Contactphone,Integer>  {


}