package com.bluntsoftware.ReachOut.modules.reachout.repository;

import com.bluntsoftware.ReachOut.modules.reachout.domain.Contactinfo;
import com.bluntsoftware.ReachOut.modules.reachout.domain.Contactweb;
import com.genx.framework.jpa.repository.GenericRepository;
import org.springframework.stereotype.Repository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.beans.factory.annotation.Qualifier;
/**
* Repository interface for table: Contactweb.
* @author autogenerated
*/

@Repository("reachoutContactwebRepository")
@Qualifier("reachout")
//@RepositoryRestResource(collectionResourceRel="reachout.Contactweb", path="reachout/Contactweb")
public interface ContactwebRepository extends GenericRepository<Contactweb,Integer>  {

}