package com.bluntsoftware.ReachOut.modules.reachout.repository;

import com.bluntsoftware.ReachOut.modules.reachout.domain.Tag;
import com.genx.framework.jpa.repository.GenericRepository;
import org.springframework.stereotype.Repository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.beans.factory.annotation.Qualifier;
/**
* Repository interface for table: Tag.
* @author autogenerated
*/

@Repository("reachoutTagRepository")
@Qualifier("reachout")
//@RepositoryRestResource(collectionResourceRel="reachout.Tag", path="reachout/Tag")
public interface TagRepository extends GenericRepository<Tag,Integer>  {

}