package com.bluntsoftware.ReachOut.modules.user_manager.repository;

import com.bluntsoftware.ReachOut.modules.user_manager.domain.ApplicationMailServer;
import com.genx.framework.jpa.repository.GenericRepository;
import org.springframework.stereotype.Repository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.beans.factory.annotation.Qualifier;
/**
* Repository interface for table: ApplicationMailServer.
* @author autogenerated
*/

@Repository("user_managerApplicationMailServerRepository")
@Qualifier("user_manager")
//@RepositoryRestResource(collectionResourceRel="user_manager.ApplicationMailServer", path="user_manager/ApplicationMailServer")
public interface ApplicationMailServerRepository extends GenericRepository<ApplicationMailServer,Integer>  {

}